### ISSUE TITLE
A problem about installation

### ISSUE THREAD

**Issue by fxths** [asyncvlsi/chp2prs#2]
I cloned chp2prs and run "make depend","make","make install". Ather that I run "make runtest".It showed that it didn't pass all tests.The result is like this. How to solve this problem?
![image](https://user-images.githubusercontent.com/61527281/97936429-6fb02400-1db6-11eb-8a6e-47a1a80f15cd.png)

**Comment by rmanohar** [comment]
Can you try the "sdtcore" branch? This will soon replace the master branch.

**Comment by fxths** [comment]
All right! thx
